name: Daily Application CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-NotificationHubs-package:
        runs-on: ubuntu-latest
        timeout-minutes: 40
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Java JDK
              uses: actions/setup-java@v2
              with:
                  distribution: "temurin"
                  java-version: 8

            - name: Publish NotificationHubs to GitHub Packages on push
              working-directory: ./NotificationHubs
              if: github.event_name == 'push'
              env:
                  GITHUB_TOKEN: ${{ github.token }}
                  MODE: ""
              run: mvn deploy

            - name: Run Maven Verify on pull request
              working-directory: ./NotificationHubs
              if: github.event_name == 'pull_request'
              env:
                  GITHUB_TOKEN: ${{ github.token }}
                  MODE: ""
              run: mvn -ntp verify
